[package]
name = "echo_server"
version = "0.1.0"
authors = ["Hahn <hahn_w@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reactor = { path = "../.." }